version: '3.8'

services:
  avios_calculator:
    image: avios_calculator:app
    container_name: avios_calculator
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - DB_URL=jdbc:postgresql://postgres_container:5432/mydatabase
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"