iagl.route.points.default: 500

spring:
  application.name: IAGL Interview Challenge
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
    data: data.sql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
  sql.init.mode: always